-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 21, 2022 at 07:00 PM
-- Server version: 10.4.19-MariaDB
-- PHP Version: 7.4.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `taxring`
--

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `sub_heading` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_key` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `short_description` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_description` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `article_image` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `title`, `slug`, `user_id`, `sub_heading`, `meta_key`, `short_description`, `meta_description`, `content`, `article_image`, `created_at`, `updated_at`) VALUES
(1, 'INCOME TAX', 'architecto-debitis-molestias', 2, NULL, NULL, 'Income tax is a type of tax that governments impose on income generated by businesses and individuals within their jurisdiction. Income tax is used to fund public services, pay government obligations, and provide goods for citizens.', NULL, '<p>Income tax is a&nbsp;<strong>type of tax that governments impose on income generated by businesses and individuals within their jurisdiction</strong>. Income tax is used to fund public services, pay government obligations, and provide goods for citizens.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>On consideration of difficulties reported by the taxpayers and other stakeholders in filing of Income Tax Returns and various reports of audit for the Assessment Year 2021-22 under the Income-tax Act, 1961(the &ldquo;Act&rdquo;), Central Board of Direct Taxes (CBDT) has decided to further extend the due dates for filing of Income Tax Returns and various reports of audit for the Assessment Year 2021-22. The details are as under:</p>\r\n\r\n<p>1. The due date of furnishing of Return of Income for the Assessment Year 2021-22, which was 31st July, 2021 under sub-section (1) of section 139 of the Act, as extended to 30th September, 2021 vide Circular No.9/2021 dated 20.05.2021, is hereby further extended to <strong>31st December, 2021;</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>2. The due date of furnishing of Report of Audit under any provision of the Act for the Previous Year 2020-21, which is 30th September, 2021, as extended to 31st October, 2021 vide Circular No.9/2021 dated 20.05.2021, is hereby further extended to 15th January, 2022;</p>\r\n\r\n<p>3. The due date of furnishing Report from an Accountant by persons entering into international transaction or specified domestic transaction under section 92E of the Act for the Previous Year 2020-21, which is 31st October, 2021, as extended to 30th November, 2021 vide Circular No.9/2021 dated 20.05.2021, is hereby further extended to 31st January, 2022;</p>\r\n\r\n<p>4. The due date of furnishing of Return of Income for the Assessment Year 2021-22, which is 31st October, 2021 under sub-section (1) of section 139 of the Act, as extended to 30th November, 2021 vide Circular No.9/2021 dated 20.05.2021, is hereby further extended to 15th February, 2022;</p>\r\n\r\n<p>5. The due date of furnishing of Return of Income for the Assessment Year 2021-22, which is 30th November, 2021 under sub-section (1) of section 139 of the Act, as extended to 31st December, 2021 vide Circular No.9/2021 dated 20.05.2021, is hereby further extended to 28th February, 2022;</p>\r\n\r\n<p>6. The due date of furnishing of belated/revised Return of Income for the Assessment Year 2021-22, which is 31st December, 2021 under sub-section (4)/sub-section (5) of section 139 of the Act, as extended to 31st January, 2022, vide Circular No.9/2021 dated 20.05.2021, is hereby further extended to 31st March, 2022;</p>\r\n\r\n<p>It is also clarified that the extension of the dates as referred to in clauses (9), (12) and (13) of Circular No.9/2021 dated 20.05.2021 and in clauses (1), (4) and (5) above shall not apply to Explanation 1 to section 234A of the Act, in cases where the amount of tax on the total income as reduced by the amount as specified in clauses (i) to (vi) of sub-section (1) of that section exceeds rupees one lakh. Further, in case of an individual resident in India referred to in sub-section (2) of section 207 of the Act, the tax paid by him under section 140A of the Act within the due date (without extension under Circular No.9/2021 dated 20.05.2021 and as above) provided in that Act, shall be deemed to be the advance tax.</p>', '{\"banner\":\"\\/\\/taxring.com\\/storage\\/banner\\/1674561741incometax-1920x700.jpg\",\"featured\":\"\\/\\/taxring.com\\/storage\\/featured\\/1674561741incometax-500x500.jpg\",\"thumbnail\":\"\\/\\/taxring.com\\/storage\\/thumbnails\\/1674561741incometax-300x300.jpg\"}', '2021-07-29 01:11:41', '2021-09-11 12:31:19'),
(22, 'COMPANY REGISTRATION & COMPLIANCE', 'company-registration-compliance', 2, NULL, NULL, 'Compliance in business refers to following the relevant laws and regulations for your industry. That means more than just the basic rules about taxes and accounting. Depending on what industry you work in, you might have to comply with large, complex sets of laws that have a significant impact on your operations.', NULL, '<p>Compliance in business refers to following the relevant laws and regulations for your industry. That means more than just the basic rules about taxes and accounting. Depending on what industry you work in, you might have to comply with large, complex sets of laws that have a significant impact on your operations.</p>', '{\"banner\":\"\\/\\/taxring.com\\/storage\\/banner\\/1030067431firmcompanyregistration-1920x700.jpg\",\"featured\":\"\\/\\/taxring.com\\/storage\\/featured\\/1030067431firmcompanyregistration-500x500.jpg\",\"thumbnail\":\"\\/\\/taxring.com\\/storage\\/thumbnails\\/1030067431firmcompanyregistration-300x300.jpg\"}', '2021-08-03 19:50:28', '2021-09-02 11:56:32'),
(21, 'GST OR GOODS & SERVICES TAX', 'gst-or-goods-services-tax', 2, NULL, NULL, 'GST, or Goods and Services Tax, is an indirect tax imposed on the supply of goods and services. It is a multi-stage, destination-oriented tax imposed on every value addition, which managed to replace multiple indirect taxes, including VAT, excise duty, service taxes, etc.', NULL, '<p>GST, or Goods and Services Tax, is an indirect tax imposed on the supply of goods and services. It is a multi-stage, destination-oriented tax imposed on every value addition, which managed to replace multiple indirect taxes, including VAT, excise duty, service taxes, etc.</p>', '{\"banner\":\"\\/\\/taxring.com\\/storage\\/banner\\/737777002blog3-1920x700.jpeg\",\"featured\":\"\\/\\/taxring.com\\/storage\\/featured\\/737777002blog3-500x500.jpeg\",\"thumbnail\":\"\\/\\/taxring.com\\/storage\\/thumbnails\\/737777002blog3-300x300.jpeg\"}', '2021-08-03 19:31:35', '2021-08-18 10:29:20'),
(23, 'A wonderful serenity has taken possession of my entire soul', 'a-wonderful-serenity-has-taken-possession-of-my-entire-soul', 2, 'Ea nihil do laborum', 'Est officia voluptat', 'I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.', 'I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.', '<p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</p>\r\n\r\n<p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p>\r\n\r\n<p>I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>\r\n\r\n<p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath</p>', '', '2022-02-14 02:00:04', '2022-05-21 16:52:28');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `articles_title_unique` (`title`),
  ADD UNIQUE KEY `articles_slug_unique` (`slug`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
